### ISSUE TITLE
Cannot fix validator errors

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok-linter#5]
In this example, a warning alert appears but it does not disappear when the code issue is resolved.
![Peek 2021-03-14 15-24](https://user-images.githubusercontent.com/4098184/111079665-abcc6180-84d9-11eb-9a33-4eb9f732cbdd.gif)

I was debugging  and the problem comes from the `Environment`, where it is stacking objects definitions instead of overwriting the file node completely:
![Selection_360](https://user-images.githubusercontent.com/4098184/111080130-d0c1d400-84db-11eb-87da-316871966752.png)

This is happening because of the way the linter re-uses the same environment in favor of performance:
https://github.com/uqbar-project/wollok-linter/blob/b3269c933f5cc2d5f63b0cfc011b66f125a45a7e/server/src/linter.ts#L45

**Comment by nscarcella** [comment]
Ooohh... Yes so, the way the linker currently works, is that, when given a previous Environment to re-link, it will merge the new packages with the old ones. When you "rename" a class from "A" to "B" the old Environment will have the old "A" class and the parser will create a new "B" class that we are not able to realize it´s the same, so it will leave both in.

I believe the error you see here is the new "B" class being highlighted with the information provided for the old "A" class.

We can think what is the most ergonomic interface to deal with the issue, but the general idea is that we need to drop the "A" class before re-linking the new parsed package. Maybe we can pass the linker a list of "dirty" nodes that need to be dropped and fill it based on the code change info.

For example, if the change that triggered the re-link goes from char position 5 to 10, we can find all nodes with presence in that range and mark them as dirty. I´m thinking in better reifying the `SourceInfo` object so it contains a more useful interface such as being able to tell if a node `isAt` a certain code offset range. Maybe we can take it from there...

What do you think @fdodino ?

**Comment by fdodino** [comment]
I think for now we can leave the linker the way it is, since performance seems to be really good (less than 200 ms):

![image](https://user-images.githubusercontent.com/4549002/130329092-85c884e3-889f-4765-9173-87b98fec613a.png)

Lets keep an eye on it while we add new validation rules, but I think we don't need to optimize this for now.
